### PR TITLE
Use DRM render nodes device for buffer allocation

### PR DESCRIPTION
**Pull request by mth**
This commit makes DRM buffer allocator to use DRM render nodes device
(/dev/dri/renderD128) and DRM_IOCTL_ROCKCHIP_GEM_CREATE, instead of main
device (/dev/dri/card0) and DRM_IOCTL_MODE_CREATE_DUMB.

Using the main DRM device requires authention with process holding the
DRM master (like X.org server). The MPP library doesn't do this, causing
non-root process with latest 4.4 kernel to get following error when using
MPP for decoding:

openat(AT_FDCWD, "/dev/dri/card0", O_RDWR) = 11
ioctl(11, DRM_IOCTL_MODE_CREATE_DUMB, 0x7fe4280f28) = 0
ioctl(11, DRM_IOCTL_PRIME_HANDLE_TO_FD, 0x7fe4280eb8) = -1 EACCES (Permission denied)

Providing authentication would complicate MPP interface and tie the library
to certain display servers.

Using render nodes and GEM buffer allocation provided by the Rockchip
DRM driver resolves the problem (now mpv plays fine using the MPP
decoder DRM_PRIME output).

### CODE REVIEW

**Comment by hizukiayaka** [comment]
Ack, But I need to check whether it works on the kernel 3.10. Also at the  kernel 4.4 from rockchip, the permission checking is disabled.

**Comment by hizukiayaka** [comment]
Sadness, it doesn't work on the kernel 3.10. Although it doesn't use the drm as the allocator currently.

**Comment by mth** [comment]
I think that the render nodes device appeared as experimental option in the 3.12 kernel. I didn't know that the DRM allocator had to work with the 3.10 kernel (as I thought that kernel was used only for Android with ION allocator). If that is the case, then this can't be solved so simply for now. Maybe it could be a build time option using preprocessor directives, as it is unlikely that single build would need to support both configurations?

**Comment by hizukiayaka** [comment]
You don't what do we use the kernel 3.10 for.

**Pull request closed without merging**
